import { HostedMcpServer, McpSkill } from './types';
import { PLATFORM_CONTROL_MCP_TOOLS } from './platform-mcp-tools';

export const HOSTED_MCP_SERVERS: HostedMcpServer[] = [
  {
    id: 'server-platform-control',
    name: 'Platform Control MCP (Direct Controllers)',
    slug: 'platform-control',
    provider: 'context-control',
    icon: 'Terminal',
    description: 'Specialized Platform Control MCP Server wrapping local in-memory controllers (<5ms) for agent blueprint engineering, BullMQ background tasks, Postgres schemas, and Auth Vault governance.',
    category: 'core',
    requiresOAuth: false,
    status: 'active',
    isSubscribed: true,
    isConnected: true,
    scopesRequired: [],
    tools: PLATFORM_CONTROL_MCP_TOOLS,
  },
  {
    id: 'server-context-control',
    name: 'Context Control Core MCP',
    slug: 'context-control',
    provider: 'context-control',
    icon: 'Layers',
    description: 'Proprietary universal context engine that resolves dynamic context profiles, memory, and RAG for agent graphs.',
    category: 'core',
    requiresOAuth: false,
    status: 'active',
    isSubscribed: true,
    isConnected: true,
    scopesRequired: [],
    tools: [
      {
        name: 'context_resolve_profile',
        description: 'Compiles and resolves multi-source context (Tenant, User, Memory, CRM, RAG) for a specific Context Profile into ready-to-use LLM context.',
        category: 'context-control',
        serverId: 'server-context-control',
        serverName: 'Context Control Core MCP',
        inputSchema: {
          type: 'object',
          properties: {
            profile_slug: {
              type: 'string',
              description: 'The target Context Profile slug (e.g., sales-agent, customer-support, code-reviewer)',
            },
            tenant_id: {
              type: 'string',
              description: 'Enterprise organization or tenant ID (e.g. acme-corp, stripe)',
            },
            user_id: {
              type: 'string',
              description: 'Identity of the end-user (e.g. usr_vip_9482)',
            },
            query: {
              type: 'string',
              description: 'The active user prompt or question to resolve relevant knowledge for',
            },
            output_format: {
              type: 'string',
              enum: ['markdown', 'json', 'structured'],
              description: 'Formatting template for the assembled context prompt',
              default: 'markdown',
            },
          },
          required: ['profile_slug', 'tenant_id', 'user_id', 'query'],
        },
      },
      {
        name: 'context_get_contract',
        description: 'Inspects the required parameters, token limits, and pipeline steps for a Context Control profile.',
        category: 'context-control',
        serverId: 'server-context-control',
        serverName: 'Context Control Core MCP',
        inputSchema: {
          type: 'object',
          properties: {
            profile_slug: {
              type: 'string',
              description: 'Profile slug to inspect contract for',
            },
          },
          required: ['profile_slug'],
        },
      },
      {
        name: 'context_list_profiles',
        description: 'Lists all available Context Control profiles, their target models, and active sources.',
        category: 'context-control',
        serverId: 'server-context-control',
        serverName: 'Context Control Core MCP',
        inputSchema: {
          type: 'object',
          properties: {},
        },
      },
      {
        name: 'agent_memory_read',
        description: 'Read structured notes or state from the agentic memory layer. Essential for long-horizon tasks when context gets compacted.',
        category: 'context-control',
        serverId: 'server-context-control',
        serverName: 'Context Control Core MCP',
        inputSchema: {
          type: 'object',
          properties: {
            topic: {
              type: 'string',
              description: 'The topic or key to retrieve from memory (e.g. "user_preferences", "current_plan")',
            },
          },
          required: ['topic'],
        },
      },
      {
        name: 'agent_memory_write',
        description: 'Write structured notes or state to the agentic memory layer to preserve data across context truncations.',
        category: 'context-control',
        serverId: 'server-context-control',
        serverName: 'Context Control Core MCP',
        inputSchema: {
          type: 'object',
          properties: {
            topic: {
              type: 'string',
              description: 'The topic or key to save under',
            },
            content: {
              type: 'string',
              description: 'The information to remember',
            },
          },
          required: ['topic', 'content'],
        },
      },
    ],
  },
  {
    id: 'server-google',
    name: 'Google Workspace MCP',
    slug: 'google-workspace',
    provider: 'google',
    icon: 'Mail',
    description: 'Hosted Google Workspace integration with 1-click OAuth to search Drive documents, draft emails, and fetch Calendar events.',
    category: 'workspace',
    requiresOAuth: true,
    oauthProvider: 'google',
    status: 'active',
    isSubscribed: true,
    isConnected: true,
    connectedUser: {
      name: 'Alex Rivera',
      email: 'alex.rivera@enterprise.io',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    },
    scopesRequired: [
      'https://www.googleapis.com/auth/drive.readonly',
      'https://www.googleapis.com/auth/gmail.compose',
      'https://www.googleapis.com/auth/calendar.events.readonly',
    ],
    tools: [
      {
        name: 'google_drive_search',
        description: 'Search for files, Google Docs, sheets, and presentations across Google Drive by keyword or query.',
        category: 'workspace',
        serverId: 'server-google',
        serverName: 'Google Workspace MCP',
        inputSchema: {
          type: 'object',
          properties: {
            query: { type: 'string', description: 'Search term or title to find in Google Drive' },
            limit: { type: 'number', description: 'Max number of files to return (1-20)', default: 5 },
          },
          required: ['query'],
        },
      },
      {
        name: 'google_gmail_send_draft',
        description: 'Create an email draft in the connected Gmail account with recipient, subject, and body text.',
        category: 'workspace',
        serverId: 'server-google',
        serverName: 'Google Workspace MCP',
        inputSchema: {
          type: 'object',
          properties: {
            to: { type: 'string', description: 'Recipient email address' },
            subject: { type: 'string', description: 'Subject line of the email' },
            body: { type: 'string', description: 'Markdown or plain text body of the draft' },
          },
          required: ['to', 'subject', 'body'],
        },
      },
      {
        name: 'google_calendar_list_events',
        description: 'Fetches upcoming Google Calendar meetings and scheduled calendar appointments for a given date range.',
        category: 'workspace',
        serverId: 'server-google',
        serverName: 'Google Workspace MCP',
        inputSchema: {
          type: 'object',
          properties: {
            daysAhead: { type: 'number', description: 'Number of upcoming days to query (default: 7)', default: 7 },
            maxResults: { type: 'number', description: 'Maximum events to return', default: 10 },
          },
        },
      },
    ],
  },
  {
    id: 'server-github',
    name: 'GitHub Hosted MCP',
    slug: 'github',
    provider: 'github',
    icon: 'Github',
    description: 'Inspect repositories, search code, read pull requests, and file issues directly from your agent graph.',
    category: 'developer',
    requiresOAuth: true,
    oauthProvider: 'github',
    status: 'active',
    isSubscribed: true,
    isConnected: true,
    connectedUser: {
      name: 'arivera-dev',
      email: 'arivera@github.com',
      avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120&auto=format&fit=crop&q=80',
    },
    scopesRequired: ['repo', 'read:user', 'read:org'],
    tools: [
      {
        name: 'github_search_repositories',
        description: 'Search public or authorized private repositories on GitHub by query string.',
        category: 'dev',
        serverId: 'server-github',
        serverName: 'GitHub Hosted MCP',
        inputSchema: {
          type: 'object',
          properties: {
            query: { type: 'string', description: 'Search term or repo qualifier (e.g. org:acme agent)' },
            sort: { type: 'string', enum: ['stars', 'updated', 'forks'], default: 'updated' },
          },
          required: ['query'],
        },
      },
      {
        name: 'github_create_issue',
        description: 'Opens a new issue in the specified repository with title, body, and labels.',
        category: 'dev',
        serverId: 'server-github',
        serverName: 'GitHub Hosted MCP',
        inputSchema: {
          type: 'object',
          properties: {
            repo: { type: 'string', description: 'Repository in format owner/name (e.g. acme/ai-engine)' },
            title: { type: 'string', description: 'Issue title' },
            body: { type: 'string', description: 'Markdown description of the bug or feature request' },
          },
          required: ['repo', 'title', 'body'],
        },
      },
      {
        name: 'github_get_pull_request',
        description: 'Fetches details, diff summary, and review status of a GitHub Pull Request.',
        category: 'dev',
        serverId: 'server-github',
        serverName: 'GitHub Hosted MCP',
        inputSchema: {
          type: 'object',
          properties: {
            repo: { type: 'string', description: 'Repository in format owner/name' },
            pullNumber: { type: 'number', description: 'PR number' },
          },
          required: ['repo', 'pullNumber'],
        },
      },
      {
        name: 'github_search_code',
        description: 'Performs semantic or regex code search within a repository.',
        category: 'dev',
        serverId: 'server-github',
        serverName: 'GitHub Hosted MCP',
        inputSchema: {
          type: 'object',
          properties: {
            repo: { type: 'string', description: 'Repository in owner/name format' },
            query: { type: 'string', description: 'Code search query or function name' },
          },
          required: ['repo', 'query'],
        },
      },
    ],
  },
  {
    id: 'server-slack',
    name: 'Slack Team MCP',
    slug: 'slack',
    provider: 'slack',
    icon: 'MessageSquare',
    description: 'Connect Slack workspaces to post notifications, broadcast agent findings, or query channel discussions.',
    category: 'productivity',
    requiresOAuth: true,
    oauthProvider: 'slack',
    status: 'active',
    isSubscribed: false,
    isConnected: false,
    scopesRequired: ['chat:write', 'channels:read', 'channels:history'],
    tools: [
      {
        name: 'slack_post_message',
        description: 'Post a message to a specific Slack channel or thread.',
        category: 'comm',
        serverId: 'server-slack',
        serverName: 'Slack Team MCP',
        inputSchema: {
          type: 'object',
          properties: {
            channel: { type: 'string', description: 'Channel name or channel ID (e.g. #announcements or C1234)' },
            text: { type: 'string', description: 'Text message to post' },
          },
          required: ['channel', 'text'],
        },
      },
      {
        name: 'slack_search_messages',
        description: 'Search Slack messages across public channels by keyword.',
        category: 'comm',
        serverId: 'server-slack',
        serverName: 'Slack Team MCP',
        inputSchema: {
          type: 'object',
          properties: {
            query: { type: 'string', description: 'Search keywords' },
            count: { type: 'number', description: 'Max messages to return', default: 5 },
          },
          required: ['query'],
        },
      },
    ],
  },
  {
    id: 'server-notion',
    name: 'Notion Knowledge MCP',
    slug: 'notion',
    provider: 'notion',
    icon: 'BookOpen',
    description: 'Index documentation, query Notion databases, and append notes to your team knowledge base.',
    category: 'productivity',
    requiresOAuth: true,
    oauthProvider: 'notion',
    status: 'active',
    isSubscribed: false,
    isConnected: false,
    scopesRequired: ['read_content', 'update_content'],
    tools: [
      {
        name: 'notion_search_pages',
        description: 'Search pages and database entries in the connected Notion workspace.',
        category: 'productivity',
        serverId: 'server-notion',
        serverName: 'Notion Knowledge MCP',
        inputSchema: {
          type: 'object',
          properties: {
            query: { type: 'string', description: 'Keywords to search in Notion titles and content' },
          },
          required: ['query'],
        },
      },
      {
        name: 'notion_append_block',
        description: 'Append text or checklist items to an existing Notion page.',
        category: 'productivity',
        serverId: 'server-notion',
        serverName: 'Notion Knowledge MCP',
        inputSchema: {
          type: 'object',
          properties: {
            pageId: { type: 'string', description: 'ID of the target Notion page' },
            content: { type: 'string', description: 'Markdown content to append' },
          },
          required: ['pageId', 'content'],
        },
      },
    ],
  },
  {
    id: 'server-postgres',
    name: 'PostgreSQL Database MCP',
    slug: 'postgres',
    provider: 'postgres',
    icon: 'Database',
    description: 'Read-only connection to production or analytics SQL databases for schema inspection and queries.',
    category: 'data',
    requiresOAuth: false,
    status: 'active',
    isSubscribed: true,
    isConnected: true,
    scopesRequired: [],
    tools: [
      {
        name: 'postgres_list_tables',
        description: 'List all available public tables and views in the connected PostgreSQL database.',
        category: 'database',
        serverId: 'server-postgres',
        serverName: 'PostgreSQL Database MCP',
        inputSchema: {
          type: 'object',
          properties: {
            schema: { type: 'string', description: 'Database schema name', default: 'public' },
          },
        },
      },
      {
        name: 'postgres_describe_table',
        description: 'Returns column names, types, primary keys, and foreign keys for a specific table.',
        category: 'database',
        serverId: 'server-postgres',
        serverName: 'PostgreSQL Database MCP',
        inputSchema: {
          type: 'object',
          properties: {
            tableName: { type: 'string', description: 'Table name to describe' },
          },
          required: ['tableName'],
        },
      },
      {
        name: 'postgres_execute_read_query',
        description: 'Executes a safe SELECT query against the connected database (with 100 row limit).',
        category: 'database',
        serverId: 'server-postgres',
        serverName: 'PostgreSQL Database MCP',
        inputSchema: {
          type: 'object',
          properties: {
            sql: { type: 'string', description: 'SQL SELECT query statement' },
          },
          required: ['sql'],
        },
      },
    ],
  },
];

export const MCP_SKILLS: McpSkill[] = [
  {
    id: 'skill-context-guard',
    name: 'Context Token Budget Guard',
    slug: 'context-budget-guard',
    category: 'context',
    description: 'Ensures tools and context injections never overflow LLM window limits, automatically optimizing token density.',
    systemPromptAddendum: 'Apply token budget preservation: synthesize data before outputting if response exceeds 2,000 tokens.',
  },
  {
    id: 'skill-safe-execution',
    name: 'Safe Tool Execution Policy',
    slug: 'safe-tool-policy',
    category: 'reasoning',
    description: 'Requires explicit human approval before invoking any destructive action (e.g. creating issues or sending emails).',
    systemPromptAddendum: 'Confirm intent with the user before performing permanent or write actions across third-party tools.',
  },
  {
    id: 'skill-crm-enrichment',
    name: 'Enterprise CRM Data Grounding',
    slug: 'crm-enrichment',
    category: 'enterprise',
    description: 'Automatically enriches company profiles, tenant SLAs, and user subscription tiers alongside tool calls.',
    systemPromptAddendum: 'Always reference the resolved tenant contract tier and user status when formulating client answers.',
  },
  {
    id: 'skill-git-code-analysis',
    name: 'Architectural Code Inspector',
    slug: 'git-code-inspector',
    category: 'coding',
    description: 'Inspects AST structures and repo conventions before proposing code or reviewing PRs.',
    systemPromptAddendum: 'Structure code suggestions using strict TypeScript types and provide file-relative imports.',
  },
];
