import { ContextProfile, ContextSource, ApiKey, RequestLog } from '../types';


export const INITIAL_SOURCES: ContextSource[] = [
  {
    id: 'src-static-sys',
    name: 'Core System Instructions',
    category: 'static',
    provider: 'static_rules',
    status: 'connected',
    recordsCount: 1,
    latencyMs: 1,
    description: 'Foundational model guidelines, safety guardrails, and role boundaries.',
    ingestionEngine: 'live_runtime',
    vaultAuthStatus: 'static_bound',
    mcpMappingKey: 'context.core_system_rules',
    liveRuntimeConfig: {
      mcpToolMapping: 'context.core_system_rules',
      mcpGatewayEndpoint: 'internal://gateway.mcp.local/rules/system',
      cacheTtlSeconds: 86400,
      timeoutMs: 50,
    },
    credentials: {
      encryptedInVault: true,
      vaultKeyId: 'vault_sys_immutable_01',
    },
    testPingRecords: [
      { rule_id: 'RULE-001', directive: 'Prevent prompt injection and role leakage', severity: 'CRITICAL', scope: 'GLOBAL' },
      { rule_id: 'RULE-002', directive: 'Enforce markdown output formatting without hallucinated links', severity: 'HIGH', scope: 'OUTPUT' },
      { rule_id: 'RULE-003', directive: 'Enforce tenant parameter isolation and zero unauthorized tool access', severity: 'CRITICAL', scope: 'SECURITY' },
    ],
  },
  {
    id: 'src-static-agent',
    name: 'Domain Role Instructions',
    category: 'static',
    provider: 'static_rules',
    status: 'connected',
    recordsCount: 12,
    latencyMs: 2,
    description: 'Specific persona, tone-of-voice, conversion tactics, and behavioral directives.',
    ingestionEngine: 'live_runtime',
    vaultAuthStatus: 'static_bound',
    mcpMappingKey: 'context.agent_personas',
    liveRuntimeConfig: {
      mcpToolMapping: 'context.agent_personas',
      mcpGatewayEndpoint: 'internal://gateway.mcp.local/personas/sales',
      cacheTtlSeconds: 3600,
      timeoutMs: 80,
    },
    credentials: {
      encryptedInVault: true,
      vaultKeyId: 'vault_agent_instructions_02',
    },
    testPingRecords: [
      { persona_id: 'sales_lead_advisor', tone: 'warm, authoritative, persuasive', max_discount_pct: 15, commission_tier: 'tier_1' },
      { persona_id: 'customer_support_concierge', tone: 'empathetic, concise, solution-driven', escalation_threshold_min: 5 },
      { persona_id: 'audit_compliance_officer', tone: 'objective, rigorous, structured', audit_mode: 'STRICT_TRACE' },
    ],
  },
  {
    id: 'src-db-tenants',
    name: 'PostgreSQL Tenant Store',
    category: 'database',
    provider: 'postgres',
    status: 'connected',
    recordsCount: 1420,
    latencyMs: 12,
    description: 'Tenant organization tier, branding rules, SLA agreements, and custom feature flags.',
    ingestionEngine: 'live_runtime',
    vaultAuthStatus: 'vault_encrypted',
    mcpMappingKey: 'db.get_tenant_config',
    liveRuntimeConfig: {
      mcpToolMapping: 'db.get_tenant_config',
      mcpGatewayEndpoint: 'https://db-proxy.contextcontrol.dev/v1/query/tenants',
      cacheTtlSeconds: 300,
      timeoutMs: 1200,
    },
    credentials: {
      connectionString: 'postgresql://postgres:••••••••@db.supabase.co:5432/postgres?sslmode=require',
      sslMode: 'require',
      encryptedInVault: true,
      vaultKeyId: 'vault_secret_pg_tenant_store',
    },
    testPingRecords: [
      { tenant_id: 'tenant_enterprise_corp', tier: 'ENTERPRISE_VIP', name: 'Acme International', features: ['live_voice', 'bullmq_queue', 'rag_unlimited'] },
      { tenant_id: 'tenant_pacific_resorts', tier: 'PRO_HOSPITALITY', name: 'Pacific Sands Resorts', features: ['crm_sync', 'multi_agent_team'] },
      { tenant_id: 'tenant_growth_fintech', tier: 'STANDARD', name: 'NovaPay Global', features: ['audit_logs', 'ephemeral_context'] },
    ],
  },
  {
    id: 'src-db-users',
    name: 'Supabase User Directory',
    category: 'database',
    provider: 'supabase',
    status: 'connected',
    recordsCount: 8940,
    latencyMs: 15,
    description: 'User profile, permissions, purchase history, past interactions, and account tenure.',
    ingestionEngine: 'batch_sync',
    vaultAuthStatus: 'rls_sandboxed',
    mcpMappingKey: 'supabase.user_profiles',
    batchSyncConfig: {
      schedule: '1h',
      cronExpression: '0 * * * *',
      nextSyncAt: '2026-09-23T16:00:00.000Z',
      embeddingModel: 'text-embedding-3-small',
      chunkSize: 512,
      targetTable: 'supabase_ephemeral_user_cache',
      bullmqQueue: 'bullmq:sync_user_directory',
      status: 'scheduled',
    },
    credentials: {
      baseUrl: 'https://api.supabase.co/rest/v1',
      apiKeyOrSecret: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9••••••••',
      encryptedInVault: true,
      vaultKeyId: 'vault_supabase_service_role',
    },
    testPingRecords: [
      { user_id: 'user_456', email: 'elena.rostova@enterprise.corp', role: 'VP_PROCUREMENT', vip_tier: 'DIAMOND', tenure_years: 4 },
      { user_id: 'user_882', email: 'marcus.vance@maui-luxury.com', role: 'GUEST_OWNER', vip_tier: 'PLATINUM', tenure_years: 2 },
      { user_id: 'user_304', email: 'carlos.santos@fintech-ops.io', role: 'ACCOUNT_ADMIN', vip_tier: 'GOLD', tenure_years: 1 },
    ],
  },
  {
    id: 'src-mem-working',
    name: 'Session Working Memory',
    category: 'memory',
    provider: 'working_memory',
    status: 'connected',
    recordsCount: 320,
    latencyMs: 4,
    description: 'Short-term scratchpad containing unresolved entities, pending commitments, and active state.',
    ingestionEngine: 'live_runtime',
    vaultAuthStatus: 'rls_sandboxed',
    mcpMappingKey: 'memory.session_scratchpad',
    liveRuntimeConfig: {
      mcpToolMapping: 'memory.session_scratchpad',
      mcpGatewayEndpoint: 'internal://redis.cluster.local/session/active',
      cacheTtlSeconds: 60,
      timeoutMs: 150,
    },
    credentials: {
      baseUrl: 'redis://redis-cluster.cache.internal:6379/1',
      encryptedInVault: true,
      vaultKeyId: 'vault_redis_working_mem',
    },
    testPingRecords: [
      { session_id: 'sess_9918a', unresolved_entity: 'Cabo San Lucas Villa Booking #882', pending_action: 'send_quote_email', confidence: 0.96 },
      { session_id: 'sess_9918b', unresolved_entity: 'Credit card decline retry alert', pending_action: 'escalate_supervisor_voice', confidence: 0.89 },
      { session_id: 'sess_9918c', unresolved_entity: 'VIP flight transfer preference', pending_action: 'append_guest_profile', confidence: 0.99 },
    ],
  },
  {
    id: 'src-mem-longterm',
    name: 'Semantic Long-Term Memory',
    category: 'memory',
    provider: 'long_term_memory',
    status: 'connected',
    recordsCount: 24500,
    latencyMs: 28,
    description: 'Vector-indexed past interactions, preferences, objections, and milestones across sessions.',
    ingestionEngine: 'batch_sync',
    vaultAuthStatus: 'vault_encrypted',
    mcpMappingKey: 'memory.semantic_longterm',
    batchSyncConfig: {
      schedule: '6h',
      cronExpression: '0 */6 * * *',
      nextSyncAt: '2026-09-23T18:00:00.000Z',
      embeddingModel: 'text-embedding-3-large',
      chunkSize: 1024,
      targetTable: 'semantic_memory_embeddings',
      bullmqQueue: 'bullmq:sync_semantic_memory',
      status: 'scheduled',
    },
    credentials: {
      collectionName: 'customer_semantic_history',
      dimension: 1536,
      encryptedInVault: true,
      vaultKeyId: 'vault_vector_longterm_store',
    },
    testPingRecords: [
      { memory_id: 'mem_0911', user_id: 'user_456', topic: 'Cancellation Resistance', summary: 'Prefers annual maintenance point waivers rather than upfront discounts.', score: 0.94 },
      { memory_id: 'mem_0912', user_id: 'user_882', topic: 'Room Upgrades', summary: 'Always requests top-floor ocean villas in Maui during August break.', score: 0.91 },
      { memory_id: 'mem_0913', user_id: 'user_304', topic: 'Payment Method', summary: 'Prefers single annual invoice on corporate Amex rather than monthly drafts.', score: 0.88 },
    ],
  },
  {
    id: 'src-conv-messages',
    name: 'Redis Message Store',
    category: 'conversation',
    provider: 'message_store',
    status: 'connected',
    recordsCount: 125000,
    latencyMs: 8,
    description: 'Current dialogue turn history, timestamps, tool calls, and user utterances.',
    ingestionEngine: 'live_runtime',
    vaultAuthStatus: 'vault_encrypted',
    mcpMappingKey: 'chat.history_lookup',
    liveRuntimeConfig: {
      mcpToolMapping: 'chat.history_lookup',
      mcpGatewayEndpoint: 'redis://cache.backend.local:6379/0',
      cacheTtlSeconds: 15,
      timeoutMs: 250,
    },
    credentials: {
      connectionString: 'redis://:••••••••@redis.east-1.cache.aws:6379',
      encryptedInVault: true,
      vaultKeyId: 'vault_redis_message_store',
    },
    testPingRecords: [
      { turn_id: 'turn_4102', role: 'user', content: 'What is the penalty if I transfer my villa points to my daughter?', timestamp: '15:28:10Z' },
      { turn_id: 'turn_4103', role: 'assistant', content: 'There is zero transfer fee for direct family members on Diamond tier.', timestamp: '15:28:12Z' },
      { turn_id: 'turn_4104', role: 'tool_call', name: 'crm.verify_family_transfer_rules', result: { status: 'eligible_zero_fee' }, timestamp: '15:28:12Z' },
    ],
  },
  {
    id: 'src-rag-knowledge',
    name: 'Qdrant Vector Knowledge Base',
    category: 'knowledge',
    provider: 'vector_rag',
    status: 'connected',
    recordsCount: 4200,
    latencyMs: 34,
    description: 'Product manuals, pricing matrices, cancellation clauses, resort perks, and FAQs.',
    ingestionEngine: 'batch_sync',
    vaultAuthStatus: 'vault_encrypted',
    mcpMappingKey: 'knowledge.qdrant_vector_search',
    batchSyncConfig: {
      schedule: '24h',
      cronExpression: '0 0 * * *',
      nextSyncAt: '2026-09-24T00:00:00.000Z',
      embeddingModel: 'text-embedding-3-small',
      chunkSize: 768,
      targetTable: 'qdrant_knowledge_chunks',
      bullmqQueue: 'bullmq:sync_qdrant_knowledge',
      status: 'scheduled',
    },
    credentials: {
      baseUrl: 'https://qdrant.cluster.cloud.qdrant.io:6333',
      apiKeyOrSecret: 'qdrant_sec_••••••••••••••••••••••••',
      collectionName: 'knowledge_base_v2',
      dimension: 1536,
      encryptedInVault: true,
      vaultKeyId: 'vault_qdrant_prod_vector',
    },
    testPingRecords: [
      { chunk_id: 'qdr_8801', title: '2026 Ownership Points Matrix.pdf', content: 'Diamond members receive 150,000 points annually with rolling 2-year rollover privileges.', similarity: 0.96 },
      { chunk_id: 'qdr_8802', title: 'Cancellation & Retention Policy.pdf', content: 'Within 72 hours of cancellation notice, advisors may issue up to 35,000 goodwill points.', similarity: 0.92 },
      { chunk_id: 'qdr_8803', title: 'Pacific Sands Resort Amenities.pdf', content: 'Complimentary yacht charter access in Cabo San Lucas for bookings exceeding 5 nights.', similarity: 0.89 },
    ],
  },
  {
    id: 'src-api-crm',
    name: 'Salesforce & Stripe Live API',
    category: 'live_data',
    provider: 'rest_api',
    status: 'connected',
    recordsCount: 50,
    latencyMs: 45,
    description: 'Live contract terms, payment status, active subscription tiers, and inventory availability.',
    ingestionEngine: 'live_runtime',
    vaultAuthStatus: 'oauth2_validated',
    mcpMappingKey: 'rest_api.get_contract',
    liveRuntimeConfig: {
      mcpToolMapping: 'rest_api.get_contract',
      mcpGatewayEndpoint: 'https://gateway.mcp.local/v1/tools/salesforce_stripe_live',
      cacheTtlSeconds: 0,
      timeoutMs: 2500,
    },
    credentials: {
      baseUrl: 'https://api.salesforce.com/services/data/v58.0',
      apiKeyOrSecret: '00D5e00000••••••••••••••••',
      encryptedInVault: true,
      vaultKeyId: 'vault_oauth_salesforce_stripe',
      headers: {
        'X-Stripe-Live': 'sk_demo_51M••••••••',
      },
    },
    testPingRecords: [
      { contract_id: 'CTR-9281', customer: 'Elena Rostova', deal_amount: 85000, stage: 'Retention_Escalated', payment_status: 'PAID_CURRENT' },
      { contract_id: 'CTR-7740', customer: 'Marcus Vance', deal_amount: 42000, stage: 'Closed_Won', payment_status: 'SCHEDULED_AUTOPAY' },
      { contract_id: 'CTR-3109', customer: 'Carlos Santos', deal_amount: 19500, stage: 'Proposal_Review', payment_status: 'PENDING_APPROVAL' },
    ],
  },
  {
    id: 'src-webhook-event',
    name: 'Webhook Event Payload',
    category: 'live_data',
    provider: 'webhook',
    status: 'connected',
    recordsCount: 1,
    latencyMs: 0,
    description: 'Direct runtime trigger payload passed along in the context resolution request.',
    ingestionEngine: 'live_runtime',
    vaultAuthStatus: 'vault_encrypted',
    mcpMappingKey: 'webhook.runtime_trigger',
    liveRuntimeConfig: {
      mcpToolMapping: 'webhook.runtime_trigger',
      mcpGatewayEndpoint: 'https://api.contextcontrol.dev/v1/context/resolve',
      cacheTtlSeconds: 0,
      timeoutMs: 100,
    },
    credentials: {
      apiKeyOrSecret: 'whsec_••••••••••••••••',
      encryptedInVault: true,
      vaultKeyId: 'vault_webhook_signing_secret',
    },
    testPingRecords: [
      { event: 'contract_cancelled', contract_id: 'CTR-9281', timestamp: '2026-09-23T15:25:00Z', risk_level: 'HIGH_VIP' },
      { event: 'inbound_call_completed', call_id: 'call_eleven_901', duration_seconds: 142, sentiment: 'ANXIOUS_OVER_FEES' },
      { event: 'calendar_event_created', event_id: 'evt_cal_401', scheduled_for: '2026-09-24T10:00:00Z', attendee: 'marcus.vance@maui.com' },
    ],
  },
];

export const INITIAL_PROFILES: ContextProfile[] = [
  {
    id: 'prof-sales-agent',
    name: 'Sales Agent',
    slug: 'sales-agent',
    description: 'Vacation Ownership Sales AI — compiles customer history, objection playbooks, and resort inventory.',
    environment: 'production',
    version: 14,
    avgTokens: 8420,
    lastRequestAt: '2 min ago',
    tags: ['Sales', 'Hospitality', 'High-Touch', 'Realtime'],
    publishedAt: '2026-08-28T14:30:00Z',
    createdAt: '2026-06-10T09:00:00Z',
    contract: {
      required: ['tenant_id'],
      optional: ['user_id', 'conversation_id', 'query'],
      runtime: {
        trigger: 'object',
      },
    },
    budget: {
      maxTokens: 12000,
      strategy: 'truncate_lowest_priority',
      outputFormat: 'markdown',
    },
    pipeline: [
      {
        id: 'step-sys',
        type: 'system_instructions',
        title: 'System Instructions',
        description: 'Global guardrails, markdown formatting rules, and tool calling etiquette.',
        sourceId: 'src-static-sys',
        priority: 10,
        enabled: true,
        config: {
          staticContent: `You are the Premier Vacation Ownership Sales Advisor for Pacific Sands Resorts.
- Always maintain an authentic, warm, and highly persuasive tone.
- Base every recommendation strictly on verified resort availability and customer profile data.
- When addressing cancellation risks, offer tailored retention points rather than aggressive pressure.`,
          tokenBudget: 350,
        },
      },
      {
        id: 'step-agent',
        type: 'agent_instructions',
        title: 'Agent Instructions',
        description: 'Specific closing tactics, discount approval boundaries, and qualification flow.',
        sourceId: 'src-static-agent',
        priority: 9,
        enabled: true,
        config: {
          staticContent: `### Sales Objective:
1. Qualify the prospect's annual vacation budget and family travel frequency.
2. Highlight high-demand villa weeks at Cabo San Lucas and Maui Bay.
3. Max authorized discount: 15% VIP waiver + 50,000 complimentary bonus points.`,
          tokenBudget: 400,
        },
      },
      {
        id: 'step-tenant',
        type: 'tenant_context',
        title: 'Tenant Context',
        description: 'Resort chain tier, branding guidelines, legal disclaimers, and state regulations.',
        sourceId: 'src-db-tenants',
        priority: 8,
        enabled: true,
        config: {
          retrievalStrategy: 'exact',
          tokenBudget: 600,
        },
      },
      {
        id: 'step-user',
        type: 'current_user',
        title: 'Current User Profile',
        description: 'Prospect details, lead score, credit pre-qualification, and past inquiries.',
        sourceId: 'src-db-users',
        priority: 8,
        enabled: true,
        config: {
          retrievalStrategy: 'exact',
          tokenBudget: 800,
        },
      },
      {
        id: 'step-working-mem',
        type: 'working_memory',
        title: 'Working Memory',
        description: 'Active session commitments, pending price quotes, and selected dates.',
        sourceId: 'src-mem-working',
        priority: 7,
        enabled: true,
        config: {
          retrievalStrategy: 'all',
          tokenBudget: 500,
        },
      },
      {
        id: 'step-longterm-mem',
        type: 'long_term_memory',
        title: 'Relevant Long-Term Memory',
        description: 'Past vacation reviews, spouse anniversary notes, and previously declined offers.',
        sourceId: 'src-mem-longterm',
        priority: 6,
        enabled: true,
        config: {
          retrievalStrategy: 'semantic',
          topK: 6,
          minimumScore: 0.72,
          tokenBudget: 2000,
        },
      },
      {
        id: 'step-conv',
        type: 'conversation',
        title: 'Conversation History',
        description: 'Recent turn exchange between prospect and sales assistant.',
        sourceId: 'src-conv-messages',
        priority: 7,
        enabled: true,
        config: {
          retrievalStrategy: 'recent_plus_relevant',
          recentMessages: 10,
          maxTokens: 2500,
        },
      },
      {
        id: 'step-rag',
        type: 'relevant_knowledge',
        title: 'Relevant Knowledge (RAG)',
        description: 'Vector-retrieved villa floor plans, deeded deed security, and exchange network rules.',
        sourceId: 'src-rag-knowledge',
        priority: 5,
        enabled: true,
        config: {
          retrievalStrategy: 'semantic',
          topK: 4,
          minimumScore: 0.75,
          tokenBudget: 2200,
        },
      },
      {
        id: 'step-live-data',
        type: 'live_data',
        title: 'Live Business Data',
        description: 'Realtime Salesforce opportunity stage & Stripe billing history.',
        sourceId: 'src-api-crm',
        priority: 6,
        enabled: true,
        config: {
          retrievalStrategy: 'exact',
          endpointUrl: 'https://api.salesforce.com/v1/opportunities',
          tokenBudget: 1000,
        },
      },
      {
        id: 'step-input',
        type: 'runtime_input',
        title: 'Runtime Input & Trigger',
        description: 'User current query or event trigger payload (e.g. contract cancellation event).',
        sourceId: 'src-webhook-event',
        priority: 10,
        enabled: true,
        config: {
          retrievalStrategy: 'webhook',
          tokenBudget: 800,
        },
      },
    ],
  },
  {
    id: 'prof-support-agent',
    name: 'Support Agent',
    slug: 'support-agent',
    description: 'Customer Support & Incident Context — resolves billing discrepancies, bug reports, and SLA tracking.',
    environment: 'production',
    version: 8,
    avgTokens: 4230,
    lastRequestAt: '12 min ago',
    tags: ['Support', 'Zendesk', 'Ticketing', 'SLA'],
    publishedAt: '2026-08-27T18:00:00Z',
    createdAt: '2026-06-15T11:00:00Z',
    contract: {
      required: ['tenant_id', 'user_id'],
      optional: ['conversation_id', 'query'],
    },
    budget: {
      maxTokens: 8000,
      strategy: 'truncate_lowest_priority',
      outputFormat: 'markdown',
    },
    pipeline: [
      {
        id: 'step-sup-sys',
        type: 'system_instructions',
        title: 'System Instructions',
        description: 'Support tone, empathy standards, and verification protocol.',
        sourceId: 'src-static-sys',
        priority: 10,
        enabled: true,
        config: {
          staticContent: `You are the Senior Technical Support Lead.
- Diagnose issues calmly and methodically.
- Verify customer account status before issuing refunds or granting elevated roles.`,
          tokenBudget: 300,
        },
      },
      {
        id: 'step-sup-tenant',
        type: 'tenant_context',
        title: 'Tenant SLA & Tier',
        description: 'Customer company plan: Enterprise, Gold, or Developer tier.',
        sourceId: 'src-db-tenants',
        priority: 8,
        enabled: true,
        config: {
          retrievalStrategy: 'exact',
          tokenBudget: 400,
        },
      },
      {
        id: 'step-sup-user',
        type: 'current_user',
        title: 'User Profile & Permissions',
        description: 'Admin rights, SSO setup, and billing contacts.',
        sourceId: 'src-db-users',
        priority: 8,
        enabled: true,
        config: {
          retrievalStrategy: 'exact',
          tokenBudget: 500,
        },
      },
      {
        id: 'step-sup-conv',
        type: 'conversation',
        title: 'Ticket Chat History',
        description: 'Prior agent notes and user messages in current ticket.',
        sourceId: 'src-conv-messages',
        priority: 7,
        enabled: true,
        config: {
          retrievalStrategy: 'recent_plus_relevant',
          recentMessages: 8,
          maxTokens: 1800,
        },
      },
      {
        id: 'step-sup-rag',
        type: 'relevant_knowledge',
        title: 'Troubleshooting Docs & KB',
        description: 'Semantic retrieval of internal debugging runbooks.',
        sourceId: 'src-rag-knowledge',
        priority: 6,
        enabled: true,
        config: {
          retrievalStrategy: 'semantic',
          topK: 3,
          minimumScore: 0.78,
          tokenBudget: 1500,
        },
      },
    ],
  },
  {
    id: 'prof-exec-copilot',
    name: 'Executive Copilot',
    slug: 'executive-copilot',
    description: 'C-Suite intelligence agent — synthesizes board metrics, runway projections, and departmental KPIs.',
    environment: 'production',
    version: 19,
    avgTokens: 6150,
    lastRequestAt: '45 min ago',
    tags: ['Executive', 'Analytics', 'Strategy'],
    publishedAt: '2026-08-28T09:15:00Z',
    createdAt: '2026-05-20T10:00:00Z',
    contract: {
      required: ['tenant_id'],
      optional: ['user_id', 'query'],
    },
    budget: {
      maxTokens: 10000,
      strategy: 'truncate_lowest_priority',
      outputFormat: 'markdown',
    },
    pipeline: [
      {
        id: 'step-exec-sys',
        type: 'system_instructions',
        title: 'System Instructions',
        description: 'Concise executive briefing format, bulleted summaries, and data rigor.',
        sourceId: 'src-static-sys',
        priority: 10,
        enabled: true,
        config: {
          staticContent: `You are the Chief Strategy Copilot.
- Deliver high-density executive briefings with executive summaries first.
- Back every assertion with verified numbers from the compiled context.`,
          tokenBudget: 350,
        },
      },
      {
        id: 'step-exec-tenant',
        type: 'tenant_context',
        title: 'Company Financial Targets',
        description: 'Annual recurring revenue targets, churn thresholds, and hiring plans.',
        sourceId: 'src-db-tenants',
        priority: 9,
        enabled: true,
        config: {
          retrievalStrategy: 'exact',
          tokenBudget: 900,
        },
      },
      {
        id: 'step-exec-live',
        type: 'live_data',
        title: 'Live Data Warehousing',
        description: 'Current month pipeline, billing collections, and active MRR.',
        sourceId: 'src-api-crm',
        priority: 8,
        enabled: true,
        config: {
          retrievalStrategy: 'exact',
          tokenBudget: 2400,
        },
      },
      {
        id: 'step-exec-rag',
        type: 'relevant_knowledge',
        title: 'Board Decks & Strategic Memos',
        description: 'Q3 Board strategy deck and competitive landscape intelligence.',
        sourceId: 'src-rag-knowledge',
        priority: 6,
        enabled: true,
        config: {
          retrievalStrategy: 'semantic',
          topK: 5,
          minimumScore: 0.70,
          tokenBudget: 2200,
        },
      },
    ],
  },
  {
    id: 'prof-auto-runner',
    name: 'Automation Runner',
    slug: 'automation-runner',
    description: 'Background automation worker — resolves context for automated webhook triggers and contract actions.',
    environment: 'staging',
    version: 4,
    avgTokens: 2840,
    lastRequestAt: '3 hours ago',
    tags: ['Automations', 'Webhooks', 'Async'],
    publishedAt: '2026-08-25T11:00:00Z',
    createdAt: '2026-07-01T15:00:00Z',
    contract: {
      required: ['tenant_id'],
      optional: ['user_id'],
      runtime: {
        trigger: 'object',
      },
    },
    budget: {
      maxTokens: 5000,
      strategy: 'hard_limit',
      outputFormat: 'json',
    },
    pipeline: [
      {
        id: 'step-auto-sys',
        type: 'system_instructions',
        title: 'System Instructions',
        description: 'Deterministic JSON task executor guidelines.',
        sourceId: 'src-static-sys',
        priority: 10,
        enabled: true,
        config: {
          staticContent: `You are an automated contract handler. Process webhook events cleanly and output strict JSON actions.`,
          tokenBudget: 250,
        },
      },
      {
        id: 'step-auto-tenant',
        type: 'tenant_context',
        title: 'Tenant Automation Policy',
        description: 'Automated retention rules, allowable refund tiers, and manager alert webhooks.',
        sourceId: 'src-db-tenants',
        priority: 9,
        enabled: true,
        config: {
          retrievalStrategy: 'exact',
          tokenBudget: 600,
        },
      },
      {
        id: 'step-auto-input',
        type: 'runtime_input',
        title: 'Webhook Event Payload',
        description: 'The incoming trigger (e.g. `contract_cancelled` event with ID CTR-9281).',
        sourceId: 'src-webhook-event',
        priority: 10,
        enabled: true,
        config: {
          retrievalStrategy: 'webhook',
          tokenBudget: 1200,
        },
      },
    ],
  },
];

export const INITIAL_API_KEYS: ApiKey[] = [
  {
    id: 'key-prod-01',
    name: 'Production Server Backend',
    key: 'ctx_live_98a72f1bc0934e81a947d102e3b8a1',
    prefix: 'ctx_live_98a...',
    environment: 'live',
    createdAt: '2026-07-01T10:00:00Z',
    lastUsedAt: 'Just now',
    scopes: ['context:resolve', 'context:read', 'profiles:read'],
    toolsWhitelist: ['crm.search_contact', 'crm.update_deal_stage', 'gmail.send_draft', 'slack.post_incident_alert'],
    rateLimitUsed: 42,
    rateLimitMax: 60,
  },
  {
    id: 'key-dev-02',
    name: 'Staging & Local Dev',
    key: 'ctx_test_41b80c94da834c89a712f00e93b4a2',
    prefix: 'ctx_test_41b...',
    environment: 'test',
    createdAt: '2026-08-15T14:20:00Z',
    lastUsedAt: '15 min ago',
    scopes: ['context:resolve', 'profiles:write', 'sources:write'],
    toolsWhitelist: ['crm.search_contact', 'postgres.describe_table', 'notion.search_pages'],
    rateLimitUsed: 12,
    rateLimitMax: 60,
  },
];

export const INITIAL_LOGS: RequestLog[] = [
  {
    id: 'req-log-9021',
    eventType: 'LANGGRAPH_EXECUTION',
    profileSlug: 'sales-agent',
    profileName: 'Enterprise Sales Pipeline Agent',
    teamBlueprintId: 'team_sales_pipeline',
    timestamp: '2 min ago',
    latencyMs: 18,
    tokenCount: 8420,
    statusCode: 200,
    statusLabel: 'SUCCESS',
    threadId: 'session_conv_789',
    checkpointId: 'ckpt_v14_turn_03',
    identity: {
      tenant_id: 'tenant_enterprise_corp',
      user_id: 'user_456',
      conversation_id: 'conversation_789',
    },
    input: {
      query: "Analyze this month's cancellations and suggest retention packages for VIP member",
      trigger: {
        type: 'contract_cancelled',
        contract_id: 'CTR-9281',
      },
    },
    sourcesUsed: ['instructions', 'tenant', 'memory', 'conversation', 'rag', 'live_data'],
    outputFormat: 'markdown',
    nodeCascade: [
      {
        stepId: 'step-1',
        name: 'Ingestion & Zod Contract Validation',
        type: 'ingestion',
        node: 'Gateway Ingest',
        detail: 'Validated payload schema against sales-agent contract & resolved tenant auth token.',
        durationMs: 2,
        status: 'completed',
        timestamp: '12:01:14.102',
      },
      {
        stepId: 'step-2',
        name: 'Supervisor Node: Intent Routing & Graph Initialization',
        type: 'supervisor',
        node: 'LangGraph Supervisor',
        detail: 'Analyzed user query; detected VIP churn intent. Delegated execution to CRM_Specialist worker.',
        durationMs: 4,
        status: 'completed',
        timestamp: '12:01:14.104',
      },
      {
        stepId: 'step-3',
        name: 'Worker Agent: CRM_Specialist Context Binding',
        type: 'worker_agent',
        node: 'CRM_Specialist',
        detail: 'Fetched account history from Supabase ephemeral_context; generated tool invocation params.',
        durationMs: 3,
        status: 'completed',
        timestamp: '12:01:14.108',
      },
      {
        stepId: 'step-4',
        name: 'MCP Gateway Tool Execution: crm.update_deal_stage',
        type: 'mcp_tool',
        node: 'HubSpot MCP Spoke',
        detail: 'Invoked crm.update_deal_stage with { deal_id: "CTR-9281", stage: "Retention_Escalated" }',
        durationMs: 7,
        status: 'completed',
        toolName: 'crm.update_deal_stage',
        timestamp: '12:01:14.111',
      },
      {
        stepId: 'step-5',
        name: 'State Checkpoint Persistence',
        type: 'checkpoint',
        node: 'PostgresSaver',
        detail: 'Saved conversation state graph turn to PostgreSQL (checkpoint: ckpt_v14_turn_03).',
        durationMs: 2,
        status: 'completed',
        timestamp: '12:01:14.118',
      },
      {
        stepId: 'step-6',
        name: 'Edge-Case Policy Evaluation',
        type: 'escalation',
        node: 'Emergency Escalation Guard',
        detail: 'Primary route succeeded with HTTP 200. ElevenLabs emergency call bypassed.',
        durationMs: 0,
        status: 'bypassed',
        timestamp: '12:01:14.120',
      },
    ],
    edgeCaseTrace: {
      policyConfigured: {
        onFailure: 'escalate',
        fallbackTool: 'elevenlabs_trigger_call',
        escalationInstructions: 'Trigger emergency voice call to lead boss if deal sync encounters network drop.',
        contactOverrides: { boss: '+1 (555) 438-9021' },
        maxRetries: 2,
      },
      evaluationStatus: 'bypassed_success',
      reason: 'Primary MCP tool crm.update_deal_stage completed successfully with code 200.',
    },
  },
  {
    id: 'task-202',
    eventType: 'BULLMQ_DELAYED',
    profileSlug: 'sales-agent',
    profileName: 'Enterprise Sales Pipeline Agent',
    teamBlueprintId: 'team_sales_pipeline',
    timestamp: '5 min ago',
    latencyMs: 11,
    tokenCount: 1250,
    statusCode: 202,
    statusLabel: 'DELAYED',
    targetTime: '2026-09-25T14:00:00.000Z',
    threadId: 'task_queue_job_202',
    identity: {
      tenant_id: 'tenant_enterprise_corp',
      user_id: 'user_456',
      conversation_id: 'thread_deferred_992',
    },
    input: {
      query: 'Automated 48-Hour Inactivity Follow-up via Gmail & Calendar Verification',
      trigger: {
        type: 'bullmq_delayed_enqueue',
        queue: 'bullmq:scheduled_tasks',
        delay_hours: 48,
      },
    },
    sourcesUsed: ['tenant', 'instructions', 'memory'],
    outputFormat: 'json',
    nodeCascade: [
      {
        stepId: 'step-1',
        name: 'Async Ingestion & Zod Validation',
        type: 'ingestion',
        node: 'POST /v1/schedule_task',
        detail: 'Validated targetTime (2026-09-25T14:00:00Z) and edgeCasePolicies payload.',
        durationMs: 3,
        status: 'completed',
        timestamp: '11:58:00.010',
      },
      {
        stepId: 'step-2',
        name: 'BullMQ Redis Delayed State Hold',
        type: 'queue',
        node: 'BullMQ Engine (Redis 7.2)',
        detail: 'Calculated delay: 172,800,000 ms (48 hours). Enqueued in Redis sorted set zset:delayed.',
        durationMs: 8,
        status: 'delayed',
        timestamp: '11:58:00.013',
      },
    ],
    edgeCaseTrace: {
      policyConfigured: {
        onFailure: 'escalate',
        fallbackTool: 'elevenlabs_trigger_call',
        escalationInstructions: 'Trigger voice alert if customer has not responded within 48h.',
        contactOverrides: { boss: '+1 (555) 438-9021' },
        maxRetries: 3,
      },
      evaluationStatus: 'bypassed_success',
      reason: 'Job currently paused in Redis sorted set until targetTime.',
    },
  },
  {
    id: 'task-204',
    eventType: 'BULLMQ_RETRY',
    profileSlug: 'support-agent',
    profileName: 'Customer Support Concierge',
    teamBlueprintId: 'team_customer_support',
    timestamp: '9 min ago',
    latencyMs: 145,
    tokenCount: 3420,
    statusCode: 429,
    statusLabel: 'RETRYING',
    retryAttempt: { current: 2, max: 3 },
    threadId: 'thread_invoice_reconcile',
    identity: {
      tenant_id: 'tenant_enterprise_corp',
      user_id: 'user_304',
      conversation_id: 'conv_5512',
    },
    input: {
      query: 'Stripe webhook retry reconciliation: Check customer invoice dispute on charges',
      trigger: {
        type: 'webhook_failure_retry',
        error: 'RateLimitError: 429 Too Many Requests from payment gateway',
      },
    },
    sourcesUsed: ['tenant', 'user', 'conversation'],
    outputFormat: 'json',
    nodeCascade: [
      {
        stepId: 'step-1',
        name: 'Worker Execution Attempt 1',
        type: 'worker_agent',
        node: 'Billing Worker',
        detail: 'Dispatched stripe.get_invoice to payment gateway.',
        durationMs: 85,
        status: 'failed',
        timestamp: '11:54:10.020',
      },
      {
        stepId: 'step-2',
        name: 'Exponential Backoff Schedule',
        type: 'queue',
        node: 'BullMQ Retry Handler',
        detail: 'Job failed with 429. Rescheduled for attempt 2 of 3 with 5000ms jitter.',
        durationMs: 60,
        status: 'retrying',
        timestamp: '11:54:10.105',
      },
    ],
    edgeCaseTrace: {
      policyConfigured: {
        onFailure: 'retry',
        fallbackTool: 'slack_post_incident_alert',
        escalationInstructions: 'Post to #ops-billing-alerts if retry loop exhausts 3 attempts.',
        maxRetries: 3,
      },
      evaluationStatus: 'retrying_queued',
      reason: 'Attempt 2 in progress with exponential backoff.',
    },
  },
  {
    id: 'task-205',
    eventType: 'ESCALATION_ALERT',
    profileSlug: 'sales-agent',
    profileName: 'Enterprise Sales Pipeline Agent',
    teamBlueprintId: 'team_sales_pipeline',
    timestamp: '18 min ago',
    latencyMs: 240,
    tokenCount: 9120,
    statusCode: 500,
    statusLabel: 'ESCALATED',
    threadId: 'sim_thread_critical_deal',
    checkpointId: 'ckpt_v12_escalation',
    identity: {
      tenant_id: 'tenant_enterprise_corp',
      user_id: 'user_vip_991',
      conversation_id: 'conv_vip_cabo',
    },
    input: {
      query: 'Critical Deal Closing: Vacation Club Diamond Ownership Contract $85,000',
      trigger: {
        type: 'primary_tool_drop',
        error: 'HubSpot API ETIMEDOUT (504 Gateway Timeout)',
      },
    },
    sourcesUsed: ['instructions', 'tenant', 'memory', 'conversation', 'rag', 'live_data'],
    outputFormat: 'markdown',
    nodeCascade: [
      {
        stepId: 'step-1',
        name: 'LangGraph Supervisor Routing',
        type: 'supervisor',
        node: 'Supervisor Node',
        detail: 'Dispatched high-value contract signoff to CRM Specialist.',
        durationMs: 5,
        status: 'completed',
        timestamp: '11:45:00.010',
      },
      {
        stepId: 'step-2',
        name: 'Primary Tool Outage Detected',
        type: 'mcp_tool',
        node: 'HubSpot MCP Spoke',
        detail: 'crm.update_deal_stage failed with 504 Gateway Timeout.',
        durationMs: 180,
        status: 'failed',
        toolName: 'crm.update_deal_stage',
        timestamp: '11:45:00.190',
      },
      {
        stepId: 'step-3',
        name: 'Emergency EdgeCasePolicy Triggered',
        type: 'escalation',
        node: 'ElevenLabs Voice Dispatcher',
        detail: '🚨 Escalated to boss (+1 (555) 438-9021). Generated autonomous briefing call script.',
        durationMs: 55,
        status: 'escalated',
        toolName: 'elevenlabs.trigger_call',
        timestamp: '11:45:00.245',
      },
    ],
    edgeCaseTrace: {
      policyConfigured: {
        onFailure: 'escalate',
        fallbackTool: 'elevenlabs_trigger_call',
        escalationInstructions: 'Trigger emergency voice call to lead boss if deal sync encounters network drop.',
        contactOverrides: { boss: '+1 (555) 438-9021', alert_slack: '#sales-war-room' },
        maxRetries: 1,
      },
      evaluationStatus: 'escalated_triggered',
      reason: 'Primary CRM tool failed with 504 Gateway Timeout. Fallback voice alert successfully placed.',
    },
  },
  {
    id: 'req-log-9020',
    eventType: 'HTTP_RESOLVE',
    profileSlug: 'sales-agent',
    profileName: 'Enterprise Sales Pipeline Agent',
    teamBlueprintId: 'team_sales_pipeline',
    timestamp: '25 min ago',
    latencyMs: 14,
    tokenCount: 7850,
    statusCode: 200,
    statusLabel: 'SUCCESS',
    threadId: 'conversation_410',
    identity: {
      tenant_id: 'tenant_enterprise_corp',
      user_id: 'user_882',
      conversation_id: 'conversation_410',
    },
    input: {
      query: 'Customer asks about upgrading from Ocean View Suite to Penthouse Villa in Maui',
    },
    sourcesUsed: ['instructions', 'tenant', 'user', 'memory', 'conversation', 'rag'],
    outputFormat: 'markdown',
    nodeCascade: [
      {
        stepId: 'step-1',
        name: 'Runtime Context Compilation',
        type: 'ingestion',
        node: 'Context Compiler',
        detail: 'Resolved tenant guidelines, member profile, and villa upgrade inventory rules.',
        durationMs: 14,
        status: 'completed',
        timestamp: '11:38:12.014',
      },
    ],
  },
  {
    id: 'req-log-9018',
    eventType: 'HTTP_RESOLVE',
    profileSlug: 'executive-copilot',
    profileName: 'Executive Copilot',
    teamBlueprintId: 'team_exec_intel',
    timestamp: '45 min ago',
    latencyMs: 22,
    tokenCount: 6150,
    statusCode: 200,
    statusLabel: 'SUCCESS',
    threadId: 'exec_conv_99',
    identity: {
      tenant_id: 'tenant_enterprise_corp',
      user_id: 'exec_01',
    },
    input: {
      query: 'Summarize Q3 gross churn vs new expansion ARR across hospitality enterprise segment',
    },
    sourcesUsed: ['instructions', 'tenant', 'live_data', 'rag'],
    outputFormat: 'markdown',
    nodeCascade: [
      {
        stepId: 'step-1',
        name: 'Executive Analytics Ingestion',
        type: 'ingestion',
        node: 'Context Compiler',
        detail: 'Compiled ARR financial live dataset and RAG executive metrics.',
        durationMs: 22,
        status: 'completed',
        timestamp: '11:18:04.022',
      },
    ],
  },
];
